//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JVKCRMEntities : DbContext
    {
        public JVKCRMEntities()
            : base("name=JVKCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCusBilling> tblCusBillings { get; set; }
        public virtual DbSet<tblCusContact> tblCusContacts { get; set; }
        public virtual DbSet<tblOriginDestination> tblOriginDestinations { get; set; }
    }
}
