//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCusBilling
    {
        public string CusId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CusCode { get; set; }
        public string Name { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string ADDR3 { get; set; }
        public string TEL { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<System.DateTime> LAST { get; set; }
        public string EmailTo { get; set; }
        public Nullable<decimal> OUTSTND { get; set; }
        public Nullable<decimal> MTD { get; set; }
        public Nullable<decimal> YTD { get; set; }
        public Nullable<decimal> TERM { get; set; }
        public string ACCT { get; set; }
        public string ATTN { get; set; }
        public Nullable<bool> INVOICING { get; set; }
        public Nullable<bool> WHTax { get; set; }
        public string EmId { get; set; }
        public string AddPerson { get; set; }
        public string Department { get; set; }
    }
}
