//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public string CusId { get; set; }
        public string CustomerType { get; set; }
        public string CusUTitle { get; set; }
        public string CusUFName { get; set; }
        public string CusULName { get; set; }
        public string CusUAddress { get; set; }
        public string CusUPhone { get; set; }
        public string CusUPhoneM { get; set; }
        public string CusUFax { get; set; }
        public string CusUEmail { get; set; }
        public string CusNote { get; set; }
        public string EmId { get; set; }
        public string AddPerson { get; set; }
        public string Department { get; set; }
        public string SaleName { get; set; }
        public Nullable<bool> Careof { get; set; }
        public string CareofName { get; set; }
        public string ServiceType { get; set; }
        public string EmailState { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CustomerDate { get; set; }
        public Nullable<System.TimeSpan> CustomerTime { get; set; }
    }
}
