//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCusContact
    {
        public string CusId { get; set; }
        public string ContactId { get; set; }
        public string ContactName { get; set; }
        public string ContactPhoneH { get; set; }
        public string ContactPhoneO { get; set; }
        public string ContactPhoneM { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public string EmId { get; set; }
        public string AddPerson { get; set; }
        public string Department { get; set; }
        public string CompanyofContact { get; set; }
    }
}
