//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOriginDestination
    {
        public string CusId { get; set; }
        public int No { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string EmId { get; set; }
        public string AddPerson { get; set; }
        public string Department { get; set; }
    }
}
